dayscope:
  version: v2024.12
  build: 3
  api_version: v1.2

website:
  url: localhost
  port: 3000

database:
  user: dayscope-root
  password: dayscope
  databaseName: dayscope

administrator:
  user: root
  password: dayscope
  email: dayscope.root

webhooks:
  url: https://nameless-sound-ff50.bit-frame.workers.dev/
  logs:
    sendStartup: false
    info: false
    warnings: true
    error: true
