version: v2024.12
build: 1

website:
  url: YOUR_DAYSCOPE_URL
  port: 3000

administrator:
  user: admin
  password: dayscopeadmin

webhooks:
  url: https://nameless-sound-ff50.bit-frame.workers.dev/
  logs:
    sendStartup: false
    info: false
    warnings: true
    error: true
